%{
#include "hpp.hpp"
%}
%option noyywrap yylineno
%%
#[^\n]*			{}									// # comment

\:				{ return COLON; }
\;				{ return SEMICOLON; }

0x[0-9A-Fa-f]+	{ yylval.n = strtoul(yytext,NULL,0x10); return NUM; }

const			{ return CONST; }

nop				{ yylval.op = opNOP; return CMD0; }
bye				{ yylval.op = opBYE; return CMD0; }


[a-zA-Z0-9_]+	{ yylval.s = yytext; return SYM; }	// some symbol

[ \t\r\n]+		{}									// drop spaces
.				{yyerror("lexer");}					// undetected char
